import React, { useState, useEffect, useRef } from 'react';
import {
  X,
  ExternalLink,
  Download,
  Maximize2,
  Minimize2,
  FileText,
  FileEdit,
  Printer,
  ZoomIn,
  ZoomOut,
  RotateCcw,
  Loader2,
  AlertCircle,
  Eye,
  FileCode,
} from 'lucide-react';
import { renderAsync } from 'docx-preview';

export interface DocumentPreviewModalProps {
  isOpen: boolean;
  onClose: () => void;
  title: string;
  fileUrl?: string;
  pdfUrl?: string; // Backward compatibility
  fileName?: string;
}

export const DocumentPreviewModal: React.FC<DocumentPreviewModalProps> = ({
  isOpen,
  onClose,
  title,
  fileUrl,
  pdfUrl,
  fileName,
}) => {
  const activeUrl = fileUrl || pdfUrl || '';
  const [isFullScreen, setIsFullScreen] = useState(false);
  const [loading, setLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [zoomLevel, setZoomLevel] = useState(1);
  const [docHtmlContent, setDocHtmlContent] = useState<string | null>(null);
  const [isDocxRendered, setIsDocxRendered] = useState(false);

  const docxContainerRef = useRef<HTMLDivElement>(null);
  const iframeRef = useRef<HTMLIFrameElement>(null);

  // Normalize URL
  const normalizedUrl = activeUrl.startsWith('http') || activeUrl.startsWith('blob:')
    ? activeUrl
    : `${window.location.origin}${activeUrl.startsWith('/') ? '' : '/'}${activeUrl}`;

  // Determine file type
  const checkStr = (activeUrl + ' ' + (fileName || '') + ' ' + title).toLowerCase();
  const isPdf = checkStr.includes('.pdf');
  const isWord = checkStr.includes('.doc') || checkStr.includes('.docx');
  const isImage = checkStr.includes('.png') || checkStr.includes('.jpg') || checkStr.includes('.jpeg') || checkStr.includes('.webp') || checkStr.includes('.svg');

  // Handle ESC key
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && isOpen) {
        onClose();
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isOpen, onClose]);

  // Load and process Word documents when modal opens
  useEffect(() => {
    if (!isOpen || !activeUrl || !isWord) {
      setDocHtmlContent(null);
      setIsDocxRendered(false);
      setErrorMsg(null);
      return;
    }

    let isMounted = true;
    setLoading(true);
    setErrorMsg(null);
    setDocHtmlContent(null);
    setIsDocxRendered(false);
    setZoomLevel(1);

    const loadDocument = async () => {
      try {
        const token = localStorage.getItem('bmc_access_token');
        const headers: Record<string, string> = {};
        if (token && normalizedUrl.includes(window.location.origin)) {
          headers['Authorization'] = `Bearer ${token}`;
        }

        const resp = await fetch(normalizedUrl, { headers });
        if (!resp.ok) {
          throw new Error(`Không thể tải tệp từ máy chủ (HTTP ${resp.status})`);
        }

        const blob = await resp.blob();
        if (!isMounted) return;

        // Check if file is HTML-based Word (.doc generated by BMC export or HTML Word template)
        const headerSlice = await blob.slice(0, 4000).text();
        const isHtmlWord =
          headerSlice.toLowerCase().includes('<html') ||
          headerSlice.includes('xmlns:w=') ||
          headerSlice.includes('xmlns:o=') ||
          headerSlice.includes('urn:schemas-microsoft-com:office');

        if (isHtmlWord) {
          // Read full text and inject styled A4 presentation wrapper
          const fullHtml = await blob.text();
          if (!isMounted) return;

          // Format HTML with print styles and clean page aesthetics
          const formattedHtml = `
            <!DOCTYPE html>
            <html>
              <head>
                <meta charset="utf-8" />
                <style>
                  @page {
                    size: A4;
                    margin: 20mm 20mm 20mm 20mm;
                  }
                  * {
                    box-sizing: border-box;
                  }
                  body {
                    background-color: #525659;
                    margin: 0;
                    padding: 30px 10px;
                    display: flex;
                    flex-direction: column;
                    align-items: center;
                    font-family: 'Times New Roman', Times, serif;
                  }
                  .page-container {
                    background-color: #ffffff;
                    width: 100%;
                    max-width: 860px;
                    min-height: 1100px;
                    padding: 55px 65px;
                    box-shadow: 0 8px 24px rgba(0, 0, 0, 0.35);
                    border-radius: 4px;
                    color: #0f172a;
                    line-height: 1.6;
                    font-size: 14pt;
                  }
                  table {
                    border-collapse: collapse;
                    width: 100%;
                  }
                  th, td {
                    border: 1px solid #94a3b8;
                    padding: 8px 10px;
                  }
                  th {
                    background-color: #f1f5f9;
                    font-weight: 700;
                  }
                  @media print {
                    body {
                      background-color: transparent;
                      padding: 0;
                    }
                    .page-container {
                      box-shadow: none;
                      padding: 0;
                      max-width: 100%;
                    }
                  }
                </style>
              </head>
              <body>
                <div class="page-container">
                  ${fullHtml}
                </div>
              </body>
            </html>
          `;

          setDocHtmlContent(formattedHtml);
          setLoading(false);
          return;
        }

        // True OOXML Word (.docx)
        if (docxContainerRef.current) {
          docxContainerRef.current.innerHTML = '';
          await renderAsync(blob, docxContainerRef.current, undefined, {
            inWrapper: true,
            ignoreWidth: false,
            ignoreHeight: false,
            className: 'bmc-docx-doc',
          });
          if (isMounted) {
            setIsDocxRendered(true);
            setLoading(false);
          }
        } else {
          // If ref is not yet available, wait next tick
          setTimeout(async () => {
            if (docxContainerRef.current && isMounted) {
              docxContainerRef.current.innerHTML = '';
              try {
                await renderAsync(blob, docxContainerRef.current, undefined, {
                  inWrapper: true,
                  ignoreWidth: false,
                  ignoreHeight: false,
                  className: 'bmc-docx-doc',
                });
                setIsDocxRendered(true);
              } catch (e: any) {
                setErrorMsg(
                  'Tệp Word này thuộc định dạng nhị phân Word 97-2003 (.doc). Định dạng này không hỗ trợ hiển thị trực tiếp trong trình duyệt. Vui lòng tải về để mở bằng Microsoft Word.'
                );
              } finally {
                setLoading(false);
              }
            }
          }, 50);
        }
      } catch (err: any) {
        console.error('Lỗi khi đọc tài liệu Word:', err);
        if (isMounted) {
          setErrorMsg(
            err.message?.includes('zip') || err.message?.includes('corrupted')
              ? 'Tệp Word này có định dạng nhị phân Word 97-2003 (.doc). Vui lòng bấm nút "Tải Về" để mở trực tiếp bằng Microsoft Word.'
              : `Không thể hiển thị tài liệu: ${err.message || 'Lỗi không xác định'}`
          );
          setLoading(false);
        }
      }
    };

    loadDocument();

    return () => {
      isMounted = false;
    };
  }, [isOpen, activeUrl, isWord]);

  if (!isOpen || !activeUrl) return null;

  // Print document action
  const handlePrint = () => {
    if (isPdf) {
      const iframe = iframeRef.current;
      if (iframe && iframe.contentWindow) {
        iframe.contentWindow.print();
      } else {
        window.open(normalizedUrl, '_blank')?.print();
      }
    } else if (docHtmlContent) {
      const iframe = iframeRef.current;
      if (iframe && iframe.contentWindow) {
        iframe.contentWindow.focus();
        iframe.contentWindow.print();
      }
    } else if (isDocxRendered) {
      window.print();
    }
  };

  return (
    <div
      style={{
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(15, 23, 42, 0.78)',
        backdropFilter: 'blur(5px)',
        zIndex: 9999,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: isFullScreen ? 0 : '12px',
        transition: 'all 0.2s ease',
      }}
    >
      <div
        style={{
          width: isFullScreen ? '100vw' : '96vw',
          maxWidth: isFullScreen ? '100vw' : '1600px',
          height: isFullScreen ? '100vh' : '96vh',
          backgroundColor: '#ffffff',
          borderRadius: isFullScreen ? 0 : '14px',
          display: 'flex',
          flexDirection: 'column',
          boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.35)',
          overflow: 'hidden',
        }}
      >
        {/* Modal Header */}
        <div
          style={{
            padding: '12px 20px',
            backgroundColor: '#0f172a',
            color: '#f8fafc',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            borderBottom: '1px solid #334155',
            gap: '16px',
            flexShrink: 0,
          }}
        >
          {/* Document Title & Badge */}
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px', overflow: 'hidden' }}>
            <div
              style={{
                width: '36px',
                height: '36px',
                borderRadius: '8px',
                backgroundColor: isWord
                  ? 'rgba(37, 99, 235, 0.25)'
                  : isPdf
                  ? 'rgba(239, 68, 68, 0.25)'
                  : isImage
                  ? 'rgba(16, 185, 129, 0.25)'
                  : 'rgba(100, 116, 139, 0.25)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                color: isWord ? '#60a5fa' : isPdf ? '#f87171' : isImage ? '#34d399' : '#cbd5e1',
                flexShrink: 0,
              }}
            >
              {isWord ? <FileEdit size={20} /> : isPdf ? <FileText size={20} /> : isImage ? <Eye size={20} /> : <FileCode size={20} />}
            </div>

            <div style={{ overflow: 'hidden' }}>
              <div
                style={{
                  fontWeight: 700,
                  fontSize: '14px',
                  color: '#ffffff',
                  whiteSpace: 'nowrap',
                  overflow: 'hidden',
                  textOverflow: 'ellipsis',
                }}
                title={title}
              >
                {title || 'Xem Trước Tài Liệu'}
              </div>
              <div style={{ fontSize: '11px', color: '#94a3b8', display: 'flex', alignItems: 'center', gap: '8px' }}>
                <span
                  style={{
                    backgroundColor: isWord ? '#1e3a8a' : isPdf ? '#7f1d1d' : '#064e3b',
                    color: '#e2e8f0',
                    padding: '1px 6px',
                    borderRadius: '4px',
                    fontWeight: 600,
                  }}
                >
                  {isWord ? 'Word Document (.doc / .docx)' : isPdf ? 'Bản Vẽ / Hồ Sơ PDF' : isImage ? 'Hình Ảnh' : 'Tài Liệu'}
                </span>
                <span>Trình xem trực tiếp trong trình duyệt</span>
              </div>
            </div>
          </div>

          {/* Action Toolbar */}
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px', flexShrink: 0 }}>
            {/* Zoom Controls (for Word/Image) */}
            {(isWord || isImage) && !loading && !errorMsg && (
              <div
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  backgroundColor: '#1e293b',
                  borderRadius: '6px',
                  padding: '2px 4px',
                  border: '1px solid #334155',
                  marginRight: '4px',
                }}
              >
                <button
                  onClick={() => setZoomLevel((z) => Math.max(0.6, Number((z - 0.1).toFixed(1))))}
                  title="Thu nhỏ"
                  style={{
                    background: 'transparent',
                    border: 'none',
                    color: '#94a3b8',
                    cursor: 'pointer',
                    padding: '4px',
                    display: 'flex',
                  }}
                >
                  <ZoomOut size={15} />
                </button>
                <span style={{ fontSize: '11px', color: '#e2e8f0', fontWeight: 600, minWidth: '42px', textAlign: 'center' }}>
                  {Math.round(zoomLevel * 100)}%
                </span>
                <button
                  onClick={() => setZoomLevel((z) => Math.min(2.0, Number((z + 0.1).toFixed(1))))}
                  title="Phóng to"
                  style={{
                    background: 'transparent',
                    border: 'none',
                    color: '#94a3b8',
                    cursor: 'pointer',
                    padding: '4px',
                    display: 'flex',
                  }}
                >
                  <ZoomIn size={15} />
                </button>
                <button
                  onClick={() => setZoomLevel(1)}
                  title="Đặt lại 100%"
                  style={{
                    background: 'transparent',
                    border: 'none',
                    color: '#94a3b8',
                    cursor: 'pointer',
                    padding: '4px',
                    display: 'flex',
                    borderLeft: '1px solid #334155',
                    marginLeft: '2px',
                  }}
                >
                  <RotateCcw size={13} />
                </button>
              </div>
            )}

            {/* Print Button */}
            <button
              onClick={handlePrint}
              title="In tài liệu"
              style={{
                padding: '6px 10px',
                borderRadius: '6px',
                backgroundColor: '#1e293b',
                color: '#e2e8f0',
                border: '1px solid #334155',
                cursor: 'pointer',
                display: 'inline-flex',
                alignItems: 'center',
                gap: '5px',
                fontSize: '12px',
                fontWeight: 600,
              }}
            >
              <Printer size={14} />
              <span className="hidden sm:inline">In</span>
            </button>

            {/* Open in new tab */}
            <a
              href={normalizedUrl}
              target="_blank"
              rel="noopener noreferrer"
              title="Mở trong tab mới"
              style={{
                padding: '6px 10px',
                borderRadius: '6px',
                backgroundColor: '#1e293b',
                color: '#cbd5e1',
                textDecoration: 'none',
                display: 'inline-flex',
                alignItems: 'center',
                gap: '5px',
                fontSize: '12px',
                fontWeight: 600,
                border: '1px solid #334155',
              }}
            >
              <ExternalLink size={14} />
              <span className="hidden sm:inline">Tab mới</span>
            </a>

            {/* Download */}
            <a
              href={normalizedUrl}
              download={fileName || true}
              title="Tải xuống tệp về máy tính"
              style={{
                padding: '6px 12px',
                borderRadius: '6px',
                backgroundColor: '#2563eb',
                color: '#ffffff',
                textDecoration: 'none',
                display: 'inline-flex',
                alignItems: 'center',
                gap: '6px',
                fontSize: '12px',
                fontWeight: 600,
              }}
            >
              <Download size={14} />
              <span>Tải về</span>
            </a>

            {/* Toggle Fullscreen */}
            <button
              onClick={() => setIsFullScreen(!isFullScreen)}
              title={isFullScreen ? 'Thu nhỏ cửa sổ' : 'Toàn màn hình'}
              style={{
                padding: '6px',
                borderRadius: '6px',
                backgroundColor: '#1e293b',
                color: '#cbd5e1',
                border: '1px solid #334155',
                cursor: 'pointer',
                display: 'inline-flex',
                alignItems: 'center',
              }}
            >
              {isFullScreen ? <Minimize2 size={16} /> : <Maximize2 size={16} />}
            </button>

            {/* Close */}
            <button
              onClick={onClose}
              title="Đóng (Esc)"
              style={{
                padding: '6px',
                borderRadius: '6px',
                backgroundColor: 'rgba(239, 68, 68, 0.2)',
                color: '#ef4444',
                border: '1px solid rgba(239, 68, 68, 0.4)',
                cursor: 'pointer',
                display: 'inline-flex',
                alignItems: 'center',
                marginLeft: '4px',
              }}
            >
              <X size={18} />
            </button>
          </div>
        </div>

        {/* Modal Body / Viewer Area */}
        <div
          style={{
            flex: 1,
            position: 'relative',
            backgroundColor: '#525659',
            overflow: 'auto',
            display: 'flex',
            flexDirection: 'column',
          }}
        >
          {/* Loading Indicator */}
          {loading && (
            <div
              style={{
                position: 'absolute',
                inset: 0,
                backgroundColor: '#525659',
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'center',
                justifyContent: 'center',
                color: '#ffffff',
                zIndex: 10,
                gap: '12px',
              }}
            >
              <Loader2 size={36} className="animate-spin" style={{ color: '#60a5fa' }} />
              <div style={{ fontWeight: 600, fontSize: '15px' }}>Đang nạp và định dạng nội dung tài liệu...</div>
              <div style={{ fontSize: '12px', color: '#cbd5e1' }}>Vui lòng chờ trong giây lát</div>
            </div>
          )}

          {/* Error / Binary DOC Fallback */}
          {errorMsg && (
            <div
              style={{
                margin: '40px auto',
                maxWidth: '620px',
                padding: '30px',
                backgroundColor: '#ffffff',
                borderRadius: '12px',
                boxShadow: '0 10px 25px rgba(0,0,0,0.3)',
                textAlign: 'center',
              }}
            >
              <div
                style={{
                  width: '56px',
                  height: '56px',
                  borderRadius: '50%',
                  backgroundColor: 'rgba(245, 158, 11, 0.1)',
                  color: '#d97706',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  margin: '0 auto 16px',
                }}
              >
                <AlertCircle size={30} />
              </div>
              <h3 style={{ fontSize: '1.2rem', color: '#0f172a', margin: '0 0 10px 0' }}>
                Thông Báo Định Dạng Tài Liệu
              </h3>
              <p style={{ color: '#475569', fontSize: '0.9rem', lineHeight: 1.6, marginBottom: '24px' }}>
                {errorMsg}
              </p>
              <div style={{ display: 'flex', justifyContent: 'center', gap: '12px', flexWrap: 'wrap' }}>
                <a
                  href={normalizedUrl}
                  download={fileName || true}
                  className="btn btn-primary"
                  style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', padding: '10px 20px', textDecoration: 'none' }}
                >
                  <Download size={16} /> Tải Về Mở Bằng Microsoft Word
                </a>
                <button
                  type="button"
                  className="btn btn-secondary"
                  onClick={onClose}
                  style={{ padding: '10px 16px' }}
                >
                  Đóng
                </button>
              </div>
            </div>
          )}

          {/* VIEW: PDF Viewer */}
          {isPdf && !errorMsg && (
            <iframe
              ref={iframeRef}
              src={`${normalizedUrl}#toolbar=1&navpanes=1&zoom=110`}
              title={title}
              style={{
                width: '100%',
                height: '100%',
                border: 'none',
                flex: 1,
              }}
            />
          )}

          {/* VIEW: HTML-based Word Document */}
          {isWord && docHtmlContent && !errorMsg && (
            <div
              style={{
                flex: 1,
                width: '100%',
                height: '100%',
                transform: zoomLevel !== 1 ? `scale(${zoomLevel})` : undefined,
                transformOrigin: 'top center',
                transition: 'transform 0.15s ease',
              }}
            >
              <iframe
                ref={iframeRef}
                srcDoc={docHtmlContent}
                title={title}
                style={{
                  width: '100%',
                  height: '100%',
                  border: 'none',
                  backgroundColor: '#525659',
                }}
              />
            </div>
          )}

          {/* VIEW: DOCX Container (Rendered by docx-preview) */}
          {isWord && !docHtmlContent && !errorMsg && (
            <div
              style={{
                flex: 1,
                overflow: 'auto',
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'center',
                padding: '24px 12px',
                transform: zoomLevel !== 1 ? `scale(${zoomLevel})` : undefined,
                transformOrigin: 'top center',
                transition: 'transform 0.15s ease',
              }}
            >
              <div
                ref={docxContainerRef}
                style={{
                  maxWidth: '900px',
                  width: '100%',
                  borderRadius: '4px',
                }}
              />
            </div>
          )}

          {/* VIEW: Image Viewer */}
          {isImage && !errorMsg && (
            <div
              style={{
                flex: 1,
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                padding: '24px',
                overflow: 'auto',
              }}
            >
              <img
                src={normalizedUrl}
                alt={title}
                style={{
                  maxWidth: '100%',
                  maxHeight: '100%',
                  objectFit: 'contain',
                  transform: zoomLevel !== 1 ? `scale(${zoomLevel})` : undefined,
                  transition: 'transform 0.15s ease',
                  boxShadow: '0 10px 30px rgba(0, 0, 0, 0.4)',
                  borderRadius: '6px',
                }}
              />
            </div>
          )}

          {/* VIEW: Other File Format fallback */}
          {!isPdf && !isWord && !isImage && !errorMsg && (
            <div
              style={{
                margin: '50px auto',
                maxWidth: '540px',
                padding: '32px',
                backgroundColor: '#ffffff',
                borderRadius: '12px',
                textAlign: 'center',
                boxShadow: '0 10px 25px rgba(0,0,0,0.3)',
              }}
            >
              <div
                style={{
                  width: '64px',
                  height: '64px',
                  borderRadius: '16px',
                  backgroundColor: 'rgba(37, 99, 235, 0.1)',
                  color: '#2563eb',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  margin: '0 auto 16px',
                }}
              >
                <FileText size={32} />
              </div>
              <h3 style={{ margin: '0 0 8px 0', color: '#0f172a' }}>Tệp Đính Kèm Công Trình</h3>
              <p style={{ color: '#64748b', fontSize: '0.88rem', marginBottom: '20px' }}>
                {fileName || title}
              </p>
              <a
                href={normalizedUrl}
                download={fileName || true}
                className="btn btn-primary"
                style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', padding: '10px 22px', textDecoration: 'none' }}
              >
                <Download size={16} /> Tải Tệp Về Máy Tính
              </a>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
